### ISSUE TITLE
MySQL connection times out after pt-online-schema-change run

### ISSUE THREAD

**Issue by hseffler** [liquibase/liquibase-percona#106]
When using pt-online-schema-change from liquibase via liquibase-percona the following happens for long migrations:

1. liquibase locks the database
2. pt-online-schema-change runs and executes sucessfully
3. liquibase tries to write the changelog entry and remove the lock

However the jdbc database connection that liquibase is using has gone idle in the meantime and the liquibase run fails and requires manual intervention.

db: mysql
liquibase: 3.5.1
liquibase-percona: 1.6.0

**Comment by adangel** [comment]
Do you use some specific connection properties? How long took pt-online-schema-change to run?

You are maybe running into the timeout, that the configurable server-side as [wait_timeout](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout). This is by default 8 hours.
You could try to play with [autoReconnect](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-high-availability-and-clustering.html#cj-conn-prop_autoReconnect). But according to the description, the driver will still throw a exception, so liquibase's query to write the changelog entry probably still doesn't work.

We probably need a small background thread to keep liquibase's connection alive while pt-online-schema-change uses its own connection.
