### ISSUE TITLE
Switch default branch to `main`

### ISSUE THREAD

**Issue by adangel** [liquibase/liquibase-percona#121]
Hi @r2liquibase ,

could you please change the default branch of this repository to `main`?
The release scripts use the main branch and only work this that branch, but any PR that is being created defaults to master (also the dependabot PRs...) - which makes it harder to get the release procedure right.

https://github.com/liquibase/liquibase-percona/settings/branches

![grafik](https://user-images.githubusercontent.com/1573684/122678591-c3596b80-d1e7-11eb-8d9d-516f34a5c255.png)

Thanks!

**Comment by adangel** [comment]
Hi @molivasdat , could you have a look at this? Thanks!

**Comment by molivasdat** [comment]
@adangel, I switched it from master to main.

**Comment by adangel** [comment]
Awesome, thanks!
