### ISSUE TITLE
Branch Protection settings break "Update Changelog" changelog

### ISSUE THREAD

**Issue by adangel** [liquibase/liquibase-percona#316]
With the latest settings changes for the branch protection rules of branch `main`, the workflow https://github.com/liquibase/liquibase-percona/actions/workflows/update-changelog.yml is now failing, since it can't push anymore the changes:

```
[main 9b950df] Updated CHANGELOG.md
 1 file changed, 7 insertions(+)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: New changes require approval from someone other than the last pusher.        
To https://github.com/liquibase/liquibase-percona
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/liquibase/liquibase-percona'
```

@molivasdat Could you elaborate about this configuration change? Where can I get information about these changes, given I'm the maintainer of this extension but not an admin of the github project and have no insight into the settings?
The release workflows (https://github.com/liquibase/liquibase-percona/actions/workflows/prepare-release.yml) are also going to push to the repository. Are these also failing now?

Thanks,
Andreas

**Comment by filipelautert** [comment]
Hello @adangel, thanks for the report!
@sayaliM0412 , could you help us with that?

**Comment by adangel** [comment]
@sayaliM0412 Thanks!
