### ISSUE TITLE
liquibase.exception.UnexpectedLiquibaseException: Percona exited with 255

### ISSUE THREAD

**Issue by rgmekala** [liquibase/liquibase-percona#472]
We are using the latest version of the package [ Liquibase 4.27.0 (liquibase-percona 4.27.0). Percona Toolkit 3.5.7. ] . we are getting the below error. can you please confirm whether the password-passing pt-osc command bug is fixed in this code?

```
14:17:41  [db4000.or1.omniture.com]: (1) Starting Liquibase at 20:17:39 (version 4.27.0 #1525 built at 2024-03-25 17:08+0000)
14:17:41  Liquibase Version: 4.27.0
14:17:41  Liquibase Open Source 4.27.0 by Liquibase
14:17:41  [ WARN] (main) Error: 1146-42S02: Table 'qsdb.DATABASECHANGELOGLOCK' doesn't exist
14:17:41  Running Changeset: 01-initial.sql::initialdb::boger
14:17:41  Running Changeset: 02-XENG-0000.sql::XENG-0000::jatruman
14:17:41  ERROR: Exception Details
14:17:41  ERROR: Exception Primary Class:  UnexpectedLiquibaseException
14:17:41  ERROR: Exception Primary Reason:  Percona exited with 255
14:17:41  ERROR: Exception Primary Source:  MariaDB 10.4.18-MariaDB-log
14:17:41  
14:17:41  Unexpected error running Liquibase: Migration failed for changeset 02-XENG-0000.sql::XENG-0000::jatruman:
14:17:41       Reason: liquibase.exception.UnexpectedLiquibaseException: Percona exited with 255
```

**Comment by adangel** [comment]
> password-passing pt-osc command bug is fixed 

Could you clarify which bug you are referring to?
In which component? liquibase, liquibase percona or percona toolkit?

Does it work 4.26.0?

**Comment by rgmekala** [comment]
we are trying [liquibase percona] . We are not sure what is details of the above error. We did not try the 4.26.0.

**Comment by adangel** [comment]
Exit status 255 ("Percona exited with 255") is strange, this is not listed in the documentation: https://docs.percona.com/percona-toolkit/pt-online-schema-change.html#exit-status

Is the script executable? Are all required perl modules installed? What happens if you call on the commandline manually `pt-online-schema-change --version`?

**Comment by adangel** [comment]
So, it seems something is wrong with pt-online-schema-change.
In your output above, I'm missing the line "Executing: pt-online-schema-change ...." right after "Running Changeset: 02-XENG-0000.sql::XENG-0000::jatruman" - so I have to assume, that the output above is incomplete...

The exception "Percona exited with 255" only happens, when pt-online-schema change indeed exits with 255, and this will only be the case after "Executing: pt-online-schema-change..." has been logged already. Logging is [in line 210](https://github.com/liquibase/liquibase-percona/blob/d3ca1b1cc1c7cdf5abdd307a51ac98f570329611/src/main/java/liquibase/ext/percona/PTOnlineSchemaChangeStatement.java#L210), the exception is thrown later [in line 251](https://github.com/liquibase/liquibase-percona/blob/d3ca1b1cc1c7cdf5abdd307a51ac98f570329611/src/main/java/liquibase/ext/percona/PTOnlineSchemaChangeStatement.java#L251).

You might want to set the property `liquibase.percona.ptdebug` (see [system properties](https://github.com/liquibase/liquibase-percona?tab=readme-ov-file#system-properties)) to get more info from pt-online-schema change. However, I would already expect some log output, but as "Executing: pt-online-schema-change..." is missing, there might be more lines missing.

A complete log could maybe help to investigate the problem further.

**Comment by adangel** [comment]
Closing this, as it is not reproducible and further information is missing.
Feel free to reopen, if this problem still exists and/or more information is available.
