### ISSUE TITLE
Add support for MariaDB JConnector

### ISSUE THREAD

**Issue by CyrilDevOps** [liquibase/liquibase-percona#60]
When we use MariaDB JConnector with liquibase, the URL may be different :
jdbc:(mysql|mariadb):[replication:|loadbalance:|sequential:|aurora:]//<hostDescription>[,<hostDescription>...]/[database][?<key1>=<value1>[&<key2>=<value2>]] 
https://mariadb.com/kb/en/about-mariadb-connector-j/#connection-strings

Today liquibase-percona isn't able to exctract hostname when we use MariaDB JConnector,
it is not able to extract connection password too.

**Comment by adangel** [comment]
For the integration test, an additional docker container can be started providing mariadb on a separate port: https://hub.docker.com/_/mariadb

The mariadb connector via maven is here: 

```xml
<dependency> 
    <groupId>org.mariadb.jdbc</groupId>
    <artifactId>mariadb-java-client</artifactId>
    <version>$VERSION</version>
</dependency>
```

-> https://search.maven.org/artifact/org.mariadb.jdbc/mariadb-java-client
