### ISSUE TITLE
Change maven coordinates to be org.liquibase.ext

### ISSUE THREAD

**Issue by adangel** [liquibase/liquibase-percona#66]
Currently this liquibase extension is published as [com.github.adangel.liquibase.ext:liquibase-percona](https://search.maven.org/search?q=g:com.github.adangel.liquibase.ext).
Since the source repo lives now under liquibase directly, we might change that to be [org.liquibase.ext](https://search.maven.org/search?q=g:org.liquibase.ext). That makes this extension more "official".

What do you think? @nvoxland @r2liquibase @molivasdat

**Comment by r2liquibase** [comment]
Yes! Thank you @adangel ! We'll make this happen on the upcoming extension releases for 4.3.0.

**Comment by adangel** [comment]
@r2liquibase I've prepared the groupId and version change in #77. Let me know, if I can support you with the release.

**Comment by r2liquibase** [comment]
Thanks @adangel . @nvoxland is looking at the issues with the Maven Central push. We're tying to figure out why mvn is not creating the .asc files Maven Central needs from us. Do you have any ideas? The maven sign plugin should create them in /target.

**Comment by adangel** [comment]
Hm... that seems to have something to do with the profile - the sign plugin is enabled with the profile release-sign-artifacts. I used a different profile name, and this configuration is still active - maybe that's why the new profile is not used?

There is a config for the release plugin in pluginManagement:
https://github.com/liquibase/liquibase-percona/blob/2b55fa9173cb6cec8c5701d1e9c279d0f8230956/pom.xml#L126-L136

and in plugins:
https://github.com/liquibase/liquibase-percona/blob/2b55fa9173cb6cec8c5701d1e9c279d0f8230956/pom.xml#L178-L187

I'd use the newer version (I think, 2.5.3 doesn't support reproducible builds yet). And maybe it's enough to remove "arguments" and merge the two configurations.

**Comment by r2liquibase** [comment]
Ok, getting warmer. I updated a lot of dependencies modelled on the liquibase-cassandra pom.xml. I put those in the `release` branch. But, getting a hiccup at the end. It did load up the .asc files which were missing on prior runs.

Here's the output:

`    [INFO] --- maven-install-plugin:2.4:install (default-install) @ liquibase-percona ---
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3.jar to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.jar
    [INFO] Installing /tmp/build/target/checkout/pom.xml to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.pom
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3-sources.jar to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-sources.jar
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3-javadoc.jar to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3-javadoc.jar to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3.jar.asc to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.jar.asc
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3.pom.asc to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.pom.asc
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3-sources.jar.asc to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-sources.jar.asc
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3-javadoc.jar.asc to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar.asc
    [INFO] Installing /tmp/build/target/checkout/target/liquibase-percona-4.3.3-javadoc.jar.asc to /home/jenkins/.m2/repository/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar.asc
    [INFO]
    [INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ liquibase-percona ---
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.jar
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.jar (50 kB at 34 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.pom
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.pom (20 kB at 34 kB/s)
    Downloading from sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/maven-metadata.xml
    Downloaded from sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/maven-metadata.xml (345 B at 2.0 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/maven-metadata.xml
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/maven-metadata.xml (376 B at 1.0 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-sources.jar
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-sources.jar (38 kB at 79 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar (130 kB at 340 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar (130 kB at 325 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.jar.asc
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.jar.asc (488 B at 3.7 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.pom.asc
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3.pom.asc (488 B at 2.6 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-sources.jar.asc
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-sources.jar.asc (488 B at 4.1 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar.asc
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar.asc (488 B at 3.8 kB/s)
    Uploading to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar.asc
    Uploaded to sonatype-nexus-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/liquibase/ext/liquibase-percona/4.3.3/liquibase-percona-4.3.3-javadoc.jar.asc (488 B at 3.8 kB/s)
    [INFO]
    [INFO] --- nexus-staging-maven-plugin:1.6.8:deploy (default-deploy) @ liquibase-percona ---
    [INFO] Performing local staging (local stagingDirectory="/tmp/build/target/checkout/target/nexus-staging/staging")...
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  15.953 s
    [INFO] Finished at: 2021-02-12T20:15:57Z
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (default-deploy) on project liquibase-percona: Execution default-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: Mandatory plugin parameter 'nexusUrl' should be your Nexus base URL only - for example http://localhost:8081/nexus -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.125 s
[INFO] Finished at: 2021-02-12T20:15:57Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:perform (default-cli) on project liquibase-percona: Maven execution failed, exit code: '1' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by adangel** [comment]
I guess, the nexus url should be just "<nexusUrl>https://oss.sonatype.org/</nexusUrl>" at https://github.com/liquibase/liquibase-percona/blob/f087491d9c196710fc710c0bde73d1d86e38505c/pom.xml#L213

I also noticed, that many plugins have different or missing versions now. I've changed that back, e.g. the release plugin should be  3.0.0-M1 or later otherwise the property "project.build.outputTimestamp" won't be updated automatically during prepare-release (see https://maven.apache.org/guides/mini/guide-reproducible-builds.html for the background)

I've pushed my changes to the release branch: https://github.com/liquibase/liquibase-percona/tree/release with commit https://github.com/liquibase/liquibase-percona/commit/57f012d36c45278b4b64231c72cc70739e5711e6

@r2liquibase Please try again with these changes.

**Comment by adangel** [comment]
@r2liquibase Any news update the release?

**Comment by r2liquibase** [comment]
And, we're live! https://github.com/liquibase/liquibase-percona/releases/tag/liquibase-percona-4.3.1

I had this as a pre-release and just pushed now as valid. Thanks, @adangel !!!

**Comment by adangel** [comment]
Thanks! :tada:
